language: java
before_deploy:
  - export RELEASE_PKG_FILE=$(ls target/*.deb)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: YHnzeu9Pwszv1sNRPfdyFLXBeSUtOgvrgrD9FUYqKRnOrTvEp+ng/NqVHilpgJ8siQGQ9xjzrsEuaLR/H+vezZzrk+s340C97Vyba6g4mUGy2qhxzooT9pS60VqkDICpblPwHZxGLW5gRwBK6EWon/nwZmaX0/C69cBKNH1YapaIFbMlDp2LdDIWJqsUzi7LDyGPZ41sfZYiI0dVQ1pniGa4G3JapPyTk3sy2exAzjFkCtJCXdM/zwZy97nhB5zUzazUWfgv1bmdEj6lwivMtu7yPwpeN/vcr6Yl8ke7DIKKqLEziMRhEZ/zdp/r2iCPGKpfuNvkjE3+TwTPSba0rbSP2jlW5lRLv5ZS4izKf0kzYskN2OOzEy1YA/gmc9S0Rn5kVLr72QOn/nOHGKVPj2x8QXA92ubIpAwgK8/K2nzl0d4bw/PlbTHEmjbXSeML/8brVzp3IZBjdHeg4OsRA6eWgqg0T7bi/6VoFsLDZXUXfSPMPrWAEtENl4snVlsTeCXGySbUtqVCXfSrB9Zn+s486pCjFliXprDCoWDsmgPmdFOxqYVqEeh6BPOTPp4yO2ykBpHfirJxtSDgjH1puGMI2ebQidFkD3eH37dFgl7JOG0ajMEg1zziMjBlTev7+0mhjUQSVbJQeCTBQnapioTZOqBGQvYMeso+pLD2veY=
  file: "${RELEASE_PKG_FILE}"
  on:
    tags: true
